
USE DATABASE CP_DW_DEV;

USE SCHEMA CP_MAIN_SCHEMA;

DROP TABLE CP_MAIN_SCHEMA.TEST1;
DROP TABLE CP_MAIN_SCHEMA.TEST2;
DROP TABLE CP_MAIN_SCHEMA.TEST3;
DROP TABLE CP_MAIN_SCHEMA.TEST4;
DROP TABLE CP_MAIN_SCHEMA.TEST5;

CREATE OR REPLACE TABLE CP_MAIN_SCHEMA.TEST6
( COL1 INTEGER,
  COL2 VARCHAR);
  
