
USE DATABASE CP_DW_DEV;
USE SCHEMA CP_MAIN_SCHEMA;

DROP TABLE TEST1;
DROP TABLE TEST2;
DROP TABLE TEST3;
DROP TABLE TEST4;
DROP TABLE TEST5;

CREATE OR REPLACE TABLE TEST10
( COL1 INTEGER,
  COL2 VARCHAR);
  
