
USE DATABADE CP_DW_DEV;

USE SCHEMA CP_MAIN_SCHEMA;
CREATE OR REPLACE TABLE CP_MAIN_SCHEMA.TEST1
( COL1 INTEGER,
  COL2 VARCHAR);

USE SCHEMA CP_MAIN_SCHEMA; 
CREATE OR REPLACE TABLE CP_MAIN_SCHEMA.TEST2
( COL1 INTEGER,
  COL2 INTEGER);

USE SCHEMA CP_MAIN_SCHEMA;
CREATE OR REPLACE TABLE CP_MAIN_SCHEMA.EMP
( EMPID INTEGER,
  EMPNAME VARCHAR(256));