# This workflow will trigger on both pull_request & push event's. But the Actions will only be performed on push to develop, qa & master branches.
# The build job & steps will syn S3 dev/qa/prod buckets.....
name: build-and-deploy to S3


# Define the event/event's which will trigger the workflow.
# This workflow will trigger on both pull_request & push event's.
# Once the changes are reviewed/approved/merged the job will run.
on:
  push:
    branches: [ develop, qa, master ]
  pull_request:
    branches: [ develop, qa, master ]

env:
  FILE_NAME: Prod-Build-Artifact
  
# A workflow can have one or more jobs which runs in parallel (default) or sequencially
jobs:

  gitleaks: # This job will scan for any leaks in credentials.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
  build:
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Sync aws s3 dev bucket from git
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      uses: sai-sharan/aws-s3-sync-action@v0.1.0

      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        region: 'us-west-2'
        #source: 'build'
        destination_bucket: ${{ secrets.AWS_S3_DEV_BUCKET }}
        #destination_prefix: 'wmtc'
        exclude: '.git/*'
        delete: true
        quiet: false

    - name: Upload Prod build Artifacts
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: Download-Prod-Build-Artifact
        path: ./${{ env.FILE_NAME }}
    - name: Download Prod build Artifacts
      uses: actions/download-artifact@v1.0.0
      with: 
        name: Download-Prod-Build-Artifact

    - name: Sync aws s3 qa bucket from git
      if: github.event_name == 'push' && github.ref == 'refs/heads/qa'
      uses: sai-sharan/aws-s3-sync-action@v0.1.0

      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        region: 'us-west-2'
        #source: 'build'
        destination_bucket: ${{ secrets.AWS_S3_QA_BUCKET }}
        #destination_prefix: 'wmtc'
        exclude: '.git/*'
        delete: true
        quiet: false

    - name: Sync aws s3 prod bucket from git
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: sai-sharan/aws-s3-sync-action@v0.1.0

      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        region: 'us-west-2'
        #source: 'build'
        destination_bucket: ${{ secrets.AWS_S3_PROD_BUCKET }}
        #destination_prefix: 'wmtc'
        exclude: '.git/*'
        delete: true
        quiet: false

