# This workflow will trigger on pull_request event and will syn S3 dev bucket with changes.....
name: build-and-deploy to S3


# Define the event which will trigger the workflow, in this case when a pull request is created on develop branch 
# and changes are reviewed ,approved/merged in develop branch from local branch.
on:
  push:
    branches: [ develop, qa, master ]
  #pull_request:
    #branches: [ develop, qa, master ]
  

# A workflow can have one or more jobs which runs in parallel (default) or sequencially
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checks-out  repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials & sync S3 Dev Bucket..
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_DEV_BUCKET}}/
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2

      - name: Configure AWS Credentials & sync S3 QA Bucket..
        if: github.event_name == 'push' && github.ref == 'refs/heads/qa'
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_QA_BUCKET}}/
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2