name: workflow to trigger wallmart us
on:
  push:
    branches: [ develop, qa ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: AWS S3 Sync Github Action
      uses: sai-sharan/aws-s3-sync-action@v0.1.0

      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        region: 'us-west-2'
        source: 'build'
        destination_bucket: ${{ secrets.AWS_S3_DEV_BUCKET }}
        #destination_prefix: 'wmtc'
        exclude: '.git/*'
        delete: true
        quiet: false